[package]
name = "polestar"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99"
num-derive = "0.4"
num-traits = "0.2"
parking_lot = "*"
proptest = "1.2.0"
proptest-derive = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"

petgraph = { version = "*", optional = true }

[dev-dependencies]
polestar = { path = ".", feature = ["testing"] }

[features]
default = ["diagrams", "testing"]

diagrams = ["petgraph"]
testing = []

[workspace]
members = ["holochain-polestar", "kitsune-polestar"]

[patch.crates-io]
# holo_hash = { path = "/home/michael/Holo/chain/crates/holo_hash" }
proptest-derive = { path = "/home/michael/gitfork/proptest/proptest-derive" }
