[package]
name = "polestar-patterns"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
derive_more = { workspace = true }
exhaustive = { workspace = true }
itertools = { workspace = true }
petgraph = { workspace = true }
polestar = { workspace = true }
rand = "0.9.2"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
